apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-config
  namespace: jupyter
data:
  jupyter_server_config.py: |
    import os
    
    # Basic configuration
    c.ServerApp.ip = '0.0.0.0'
    c.ServerApp.port = 8888
    c.ServerApp.open_browser = False
    c.ServerApp.token = os.environ.get('JUPYTER_TOKEN', '')
    c.ServerApp.password = ''
    c.ServerApp.allow_root = True
    c.ServerApp.root_dir = '/home/jovyan/work'
    
    # Security settings
    c.ServerApp.allow_origin = '*'
    c.ServerApp.disable_check_xsrf = True
    
    # Kernel settings
    c.KernelManager.autorestart = True
    
    # Enable Elyra extensions
    c.LabServerApp.extra_labextensions_path = ['/opt/conda/share/jupyter/labextensions']

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-workspace
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-lab
  namespace: jupyter
  labels:
    app: jupyter-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-lab
  template:
    metadata:
      labels:
        app: jupyter-lab
    spec:
      containers:
      - name: jupyter-lab
        image: quay.io/jupyter/scipy-notebook:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: jupyter
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: JUPYTER_TOKEN
          value: "datascience123"
        - name: GRANT_SUDO
          value: "yes"
        - name: CHOWN_HOME
          value: "yes"
        - name: PYTHONPATH
          value: "/home/jovyan/work"
        command:
        - start-notebook.sh
        - --ServerApp.config_file=/etc/jupyter/jupyter_server_config.py
        - --ServerApp.token=datascience123
        - --ServerApp.password=''
        - --LabApp.check_for_updates=False
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan/work
        - name: config
          mountPath: /etc/jupyter
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 4Gi
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: jupyter-workspace
      - name: config
        configMap:
          name: jupyter-config
          items:
          - key: jupyter_server_config.py
            path: jupyter_server_config.py

---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-lab-service
  namespace: jupyter
  labels:
    app: jupyter-lab
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30888
    name: jupyter
  selector:
    app: jupyter-lab
