apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
rules:
# Core Kubernetes resources for pod management
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Apps resources
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Batch resources for jobs
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Spark Operator resources
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["scheduledsparkapplications", "scheduledsparkapplications/status"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
# Extensions for networking
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
# Metrics
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: airflow
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
---
# Role for Airflow to work in default namespace (where Spark apps run)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-default-jobs
  namespace: default
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-default-jobs
  namespace: default
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-default-jobs
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
---
# Additional role for Airflow to work across namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-spark-jobs
  namespace: spark
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-spark-jobs
  namespace: spark
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-spark-jobs
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
---
# Role for Airflow to work in jupyter namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-jupyter-jobs
  namespace: jupyter
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-jupyter-jobs
  namespace: jupyter
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-jupyter-jobs
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
